"""Update articles model structure

Revision ID: c5249c41290a
Revises: 2760376d9bad
Create Date: 2025-06-24 10:43:59.905195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5249c41290a'
down_revision = '2760376d9bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('featured_image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('reading_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=False))
        batch_op.alter_column('content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('content_body',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('article_status',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('like_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('comment_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('share_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('allow_comments',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_articles_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_featured'), ['featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_like_count'), ['like_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_articles_title'), ['title'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['user_id'])

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'contents', ['content_id'], ['content_id'])

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('idx_tags_is_active')
        batch_op.drop_constraint('tags_name_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))
        batch_op.create_unique_constraint('tags_name_key', ['name'])
        batch_op.create_index('idx_tags_is_active', ['is_active'], unique=False)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_articles_title'))
        batch_op.drop_index(batch_op.f('ix_articles_slug'))
        batch_op.drop_index(batch_op.f('ix_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_articles_like_count'))
        batch_op.drop_index(batch_op.f('ix_articles_featured'))
        batch_op.drop_index(batch_op.f('ix_articles_created_at'))
        batch_op.drop_index(batch_op.f('ix_articles_category'))
        batch_op.drop_index(batch_op.f('ix_articles_author_id'))
        batch_op.alter_column('allow_comments',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('share_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('comment_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('like_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('article_status',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('content_body',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('content_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('views')
        batch_op.drop_column('likes')
        batch_op.drop_column('reading_time')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('slug')
        batch_op.drop_column('tags')
        batch_op.drop_column('category')
        batch_op.drop_column('featured')
        batch_op.drop_column('status')
        batch_op.drop_column('published_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('author_id')
        batch_op.drop_column('featured_image_url')
        batch_op.drop_column('content')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
